apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: demo
  labels:
    owner: team-platform
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          owner: team-platform
  data:
    - secretKey: password
      remoteRef:
        key: demo/db/password
